### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by AndiDog**
Fixes https://github.com/giantswarm/roadmap/issues/1469

### CODE REVIEW

**Comment by calvix** [comment]
can we also bump all these imports
```
capa "sigs.k8s.io/cluster-api-provider-aws/api/v1alpha3"
expcapa "sigs.k8s.io/cluster-api-provider-aws/exp/api/v1alpha3"
capi "sigs.k8s.io/cluster-api/api/v1alpha3"
```

to v1beta2/v1beta1 ?

**Comment by AndiDog** [comment]
I upgraded to CAPA v2. Any problem with that? Do you think I should test this change (IMO yes)?

**Comment by calvix** [comment]
upgrading to v2 should be fine, if you can create a cluster with this `capa-iam-operator` deployed than we should be fine so I would test that

**Review by calvix — APPROVED** [review]
lgtm

**Comment by AndiDog** [comment]
Upgrading to CAPA v2 isn't working right now since we use v1.5.2 CRDs. This operator therefore fails to start:

```
controller-runtime/source "msg"="if kind is a CRD, it should be installed before calling Start" "error"="no matches for kind \"AWSMachinePool\" in version \"infrastructure.cluster.x-k8s.io/v1beta2\"" "kind"={"Group":"infrastructure.cluster.x-k8s.io","Kind":"AWSMachinePool"}

controller-runtime/source "msg"="if kind is a CRD, it should be installed before calling Start" "error"="no matches for kind \"AWSMachineTemplate\" in version \"infrastructure.cluster.x-k8s.io/v1beta2\"" "kind"={"Group":"infrastructure.cluster.x-k8s.io","Kind":"AWSMachineTemplate"}
```

Since the CRD upgrade likely isn't trivial, I will create a separate issue for it, and downgrade dependencies for this PR again to CAPA ~ v1.5.2 (v1beta1).

**Review by calvix — APPROVED** [review]
lgtm

**Pull request merged**
